import 'package:flutter/material.dart';
import '../../core/navigation/app_routes.dart';
import '../../core/state/app_state_provider.dart';
import '../../core/theme/app_colors.dart';
import '../../core/theme/app_typography.dart';
import '../../widgets/common/cortex_button.dart';
import '../../widgets/common/cortex_card.dart';
import '../../widgets/common/cortex_text_field.dart';

class MfaVerificationScreen extends StatefulWidget {
  const MfaVerificationScreen({super.key});

  @override
  State<MfaVerificationScreen> createState() => _MfaVerificationScreenState();
}

class _MfaVerificationScreenState extends State<MfaVerificationScreen> {
  final TextEditingController codeController = TextEditingController();
  bool isLoading = false;
  String? errorMessage;

  @override
  void dispose() {
    codeController.dispose();
    super.dispose();
  }

  Future<void> _verifyCode() async {
    final code = codeController.text.trim();
    if (code.length < 6) {
      setState(() => errorMessage = 'Please enter a 6-digit verification code.');
      return;
    }

    setState(() {
      isLoading = true;
      errorMessage = null;
    });

    final appState = AppStateProvider.of(context);
    final success = await appState.verifyMfa(code);

    if (!mounted) return;
    setState(() => isLoading = false);

    if (success) {
      Navigator.pushNamedAndRemoveUntil(context, AppRoutes.home, (route) => false);
    } else {
      setState(() => errorMessage = 'Invalid authentication code. Try demo code: 123456');
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.background,
      appBar: AppBar(
        backgroundColor: Colors.transparent,
        elevation: 0,
        leading: IconButton(
          onPressed: () => Navigator.of(context).pop(),
          icon: const Icon(Icons.arrow_back_ios_new_rounded, size: 18),
        ),
      ),
      body: SafeArea(
        child: Center(
          child: SingleChildScrollView(
            padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 20),
            child: ConstrainedBox(
              constraints: const BoxConstraints(maxWidth: 440),
              child: Column(
                children: [
                  Container(
                    width: 64,
                    height: 64,
                    decoration: BoxDecoration(
                      color: AppColors.surfaceElevated,
                      shape: BoxShape.circle,
                      border: Border.all(color: AppColors.accentCyan, width: 1.2),
                    ),
                    child: const Icon(
                      Icons.lock_clock_rounded,
                      size: 32,
                      color: AppColors.accentCyan,
                    ),
                  ),

                  const SizedBox(height: 20),

                  const Text(
                    'SECURITY VERIFICATION (MFA)',
                    style: TextStyle(
                      fontSize: 18,
                      fontWeight: FontWeight.bold,
                      letterSpacing: 1.2,
                      color: AppColors.textPrimary,
                    ),
                  ),

                  const SizedBox(height: 6),

                  const Text(
                    'Enter the 6-digit TOTP token generated by your cryptographic authenticator device.',
                    textAlign: TextAlign.center,
                    style: AppTypography.bodySmall,
                  ),

                  const SizedBox(height: 28),

                  CortexCard(
                    padding: const EdgeInsets.all(22),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.stretch,
                      children: [
                        CortexTextField(
                          controller: codeController,
                          labelText: 'AUTHENTICATOR PIN (6 DIGITS)',
                          hintText: 'e.g. 123456',
                          prefixIcon: Icons.pin_rounded,
                          keyboardType: TextInputType.number,
                          autoFocus: true,
                          onSubmitted: (_) => _verifyCode(),
                        ),

                        const SizedBox(height: 12),

                        Row(
                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                          children: [
                            const Text(
                              'Demo code: 123456',
                              style: TextStyle(
                                color: AppColors.textMuted,
                                fontSize: 11,
                                fontFamily: 'monospace',
                              ),
                            ),
                            TextButton(
                              onPressed: () {
                                codeController.text = '123456';
                                _verifyCode();
                              },
                              child: const Text('Auto-fill', style: TextStyle(fontSize: 12)),
                            ),
                          ],
                        ),

                        if (errorMessage != null) ...[
                          const SizedBox(height: 10),
                          Text(
                            errorMessage!,
                            style: const TextStyle(color: AppColors.error, fontSize: 12),
                          ),
                        ],

                        const SizedBox(height: 20),

                        CortexButton(
                          text: 'VERIFY & ENTER COMMAND',
                          icon: Icons.check_circle_outline_rounded,
                          isLoading: isLoading,
                          onPressed: _verifyCode,
                        ),
                      ],
                    ),
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}
